[package]
name = "osmio"
version = "0.6.0-rc1"
authors = ["Amanda McCann <amanda@technomancy.org>"]
keywords = ["openstreetmap", "osm"]
license = "AGPL-3.0"
repository = "https://github.com/amandasaurus/osmio/"
description = "Read and write OpenStreetMap data files"

[dependencies]
xml-rs = "0.8.0"
protobuf = "~2.8.1"
byteorder = "1.3.2"
flate2 = "1.0.12"
chrono = "0.4.9"
separator = "0.4.1"
derive_builder = "0.10.2"
quick-xml = "0.22.0"

bzip2 = "0.4"
